allowBuilds:
  '@firebase/util': true
  core-js: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@firebase/util'
  - protobufjs
