// ============================================================
// bCampus Chat Worker — Message Repository
// ============================================================
// Pure DB access — no business logic, no auth.

import { and, eq, lt, or, desc, inArray, max, sql } from "drizzle-orm";
import type { Database } from "../../db/drizzle";
import {
	messages,
	messageAttachments,
	messageIdempotency,
	roomEvents,
	rooms,
} from "../../db/schema";
import type { Message, MessageAttachment } from "../../db/schema";
import { MESSAGE_PAGE_SIZE } from "../../constants";

export interface MessageWithAttachments extends Message {
	attachments: MessageAttachment[];
}

export interface CreateMessageInput {
	id: string;
	roomId: string;
	authorUid: string;
	replyToMessageId: string | null;
	type: Message["type"];
	content: string;
	createdAt?: string;
	updatedAt?: string;
}

export interface CreateAttachmentInput {
	messageId: string;
	type: MessageAttachment["type"];
	displayOrder: number;
	originalFileName: string;
	mimeType: string;
	fileSize: number;
	storageKey: string;
	id?: string;
	createdAt?: string;
}

export interface CreateRoomEventInput {
	roomId: string;
	roomSeq: number;
	eventId: string;
	eventType: string;
	aggregateId: string | null;
	payload: Record<string, unknown>;
}

export interface CreateMessageIdempotencyInput {
	roomId: string;
	authorUid: string;
	key: string;
	messageId: string;
}

export interface PaginationCursor {
	createdAt: string;
	id: string;
}

export class MessageRepository {
	constructor(private readonly db: Database) {}

	// ----------------------------------------------------------------
	// Create message (no attachments)
	// ----------------------------------------------------------------
	async create(input: CreateMessageInput): Promise<Message> {
		const rows = await this.db
			.insert(messages)
			.values({
				id: input.id,
				roomId: input.roomId,
				authorUid: input.authorUid,
				replyToMessageId: input.replyToMessageId,
				type: input.type,
				content: input.content,
				createdAt: input.createdAt,
				updatedAt: input.updatedAt,
			})
			.returning();
		return rows[0]!;
	}

	/**
	 * Persist a message, its attachments, and the room counter atomically.
	 *
	 * Neon's supported HTTP batch API sends these statements in one request.
	 * The old write path did the insert and counter update as two sequential
	 * requests, so this removes a full network RTT while also keeping the
	 * message/attachment/counter changes atomic at the database boundary.
	 */
	async createWithAttachmentsAndRoomCounter(
		msgInput: CreateMessageInput,
		attachmentInputs: CreateAttachmentInput[],
		eventInput?: CreateRoomEventInput,
		idempotencyInput?: CreateMessageIdempotencyInput,
	): Promise<MessageWithAttachments> {
		const messageQuery = this.db
			.insert(messages)
			.values({
				id: msgInput.id,
				roomId: msgInput.roomId,
				authorUid: msgInput.authorUid,
				replyToMessageId: msgInput.replyToMessageId,
				type: msgInput.type,
				content: msgInput.content,
				createdAt: msgInput.createdAt,
				updatedAt: msgInput.updatedAt,
			})
			.returning();
		const counterQuery = this.db
			.update(rooms)
			.set({
				messageCount: sql`${rooms.messageCount} + 1`,
				// Both timestamps are generated by the same database request. This
				// avoids a second round-trip just to read createdAt before updating
				// the room metadata.
				lastMessageAt: sql`CURRENT_TIMESTAMP`,
				updatedAt: sql`CURRENT_TIMESTAMP`,
			})
			.where(eq(rooms.id, msgInput.roomId));
		const eventQuery = eventInput
			? this.db.insert(roomEvents).values({
					roomId: eventInput.roomId,
					roomSeq: eventInput.roomSeq,
					eventId: eventInput.eventId,
					eventType: eventInput.eventType,
					aggregateId: eventInput.aggregateId,
					payload: eventInput.payload,
				})
			: null;
		const idempotencyQuery = idempotencyInput
			? this.db.insert(messageIdempotency).values({
					roomId: idempotencyInput.roomId,
					authorUid: idempotencyInput.authorUid,
					key: idempotencyInput.key,
					messageId: idempotencyInput.messageId,
				})
			: null;

		if (attachmentInputs.length === 0) {
			let rows;
			if (eventQuery && idempotencyQuery) {
				[rows] = await this.db.batch([
					messageQuery,
					counterQuery,
					eventQuery,
					idempotencyQuery,
				] as const);
			} else if (eventQuery) {
				[rows] = await this.db.batch([messageQuery, counterQuery, eventQuery] as const);
			} else if (idempotencyQuery) {
				[rows] = await this.db.batch([messageQuery, counterQuery, idempotencyQuery] as const);
			} else {
				[rows] = await this.db.batch([messageQuery, counterQuery] as const);
			}
			const msg = rows[0];
			if (!msg) throw new Error("Message insert returned no row");
			return { ...msg, attachments: [] };
		}

		const attachmentQuery = this.db
			.insert(messageAttachments)
			.values(attachmentInputs.map((attachment) => ({
				...attachment,
				id: attachment.id,
				createdAt: attachment.createdAt,
			})))
			.returning();
		let rows;
		let atts;
		if (eventQuery && idempotencyQuery) {
			[rows, atts] = await this.db.batch([
				messageQuery,
				attachmentQuery,
				counterQuery,
				eventQuery,
				idempotencyQuery,
			] as const);
		} else if (eventQuery) {
			[rows, atts] = await this.db.batch([
				messageQuery,
				attachmentQuery,
				counterQuery,
				eventQuery,
			] as const);
		} else if (idempotencyQuery) {
			[rows, atts] = await this.db.batch([
				messageQuery,
				attachmentQuery,
				counterQuery,
				idempotencyQuery,
			] as const);
		} else {
			[rows, atts] = await this.db.batch([
				messageQuery,
				attachmentQuery,
				counterQuery,
			] as const);
		}
		const msg = rows[0];
		if (!msg) throw new Error("Message insert returned no row");
		return { ...msg, attachments: atts };
	}

	/** Finds the message committed for a retried command. */
	async findByIdempotencyKey(
		roomId: string,
		authorUid: string,
		key: string,
	): Promise<MessageWithAttachments | null> {
		const rows = await this.db
			.select({ messageId: messageIdempotency.messageId })
			.from(messageIdempotency)
			.where(
				and(
					eq(messageIdempotency.roomId, roomId),
					eq(messageIdempotency.authorUid, authorUid),
					eq(messageIdempotency.key, key),
				),
			)
			.limit(1);
		return rows[0] ? this.findByIdWithAttachments(rows[0].messageId) : null;
	}

	/** Returns the committed event high-water mark for sequence repair. */
	async getRoomEventHighWater(roomId: string): Promise<number> {
		const rows = await this.db
			.select({ highWater: max(roomEvents.roomSeq) })
			.from(roomEvents)
			.where(eq(roomEvents.roomId, roomId));
		const value = rows[0]?.highWater;
		return value === null || value === undefined ? 0 : Number(value);
	}

	// ----------------------------------------------------------------
	// Reads
	// ----------------------------------------------------------------
	async findById(id: string): Promise<Message | null> {
		const rows = await this.db
			.select()
			.from(messages)
			.where(eq(messages.id, id))
			.limit(1);
		return rows[0] ?? null;
	}

	async findByIdWithAttachments(id: string): Promise<MessageWithAttachments | null> {
		const msg = await this.findById(id);
		if (!msg) return null;
		const attachments = await this.db
			.select()
			.from(messageAttachments)
			.where(eq(messageAttachments.messageId, id))
			.orderBy(messageAttachments.displayOrder);
		return { ...msg, attachments };
	}

	async listByRoom(
		roomId: string,
		limit: number = MESSAGE_PAGE_SIZE,
		cursor?: PaginationCursor,
	): Promise<MessageWithAttachments[]> {
		const fetchLimit = limit + 1; // one extra to detect hasMore

		const rows = cursor
			? await this.db
					.select()
					.from(messages)
					.where(
						and(
							eq(messages.roomId, roomId),
							or(
								lt(messages.createdAt, cursor.createdAt),
								and(
									eq(messages.createdAt, cursor.createdAt),
									lt(messages.id, cursor.id),
								),
							),
						),
					)
					.orderBy(desc(messages.createdAt), desc(messages.id))
					.limit(fetchLimit)
			: await this.db
					.select()
					.from(messages)
					.where(eq(messages.roomId, roomId))
					.orderBy(desc(messages.createdAt), desc(messages.id))
					.limit(fetchLimit);

		if (rows.length === 0) return [];

		// Batch-load all attachments in one query — avoids N+1
		const msgIds = rows.map((m) => m.id);
		const allAttachments = await this.db
			.select()
			.from(messageAttachments)
			.where(inArray(messageAttachments.messageId, msgIds))
			.orderBy(messageAttachments.displayOrder);

		const attachMap = new Map<string, MessageAttachment[]>();
		for (const att of allAttachments) {
			const list = attachMap.get(att.messageId) ?? [];
			list.push(att);
			attachMap.set(att.messageId, list);
		}

		return rows.map((m) => ({ ...m, attachments: attachMap.get(m.id) ?? [] }));
	}

	// ----------------------------------------------------------------
	// Writes
	// ----------------------------------------------------------------

	/** Soft-delete: sets visibility=DELETED, deletedAt, clears content */
	async softDelete(id: string): Promise<Message | null> {
		const now = new Date().toISOString();
		// content is set to a single space because the chk_text_message constraint
		// requires LENGTH(TRIM(content)) > 0 for TEXT messages. The DELETED visibility
		// signals to all consumers that the message content is gone.
		const rows = await this.db
			.update(messages)
			.set({
				visibility: "DELETED",
				content: " ", // satisfies chk_text_message; consumers must check visibility
				deletedAt: now,
				updatedAt: now,
			})
			.where(eq(messages.id, id))
			.returning();
		return rows[0] ?? null;
	}

	/** Hide from regular users — pending moderator review */
	async hide(id: string): Promise<Message | null> {
		const rows = await this.db
			.update(messages)
			.set({ visibility: "HIDDEN", updatedAt: new Date().toISOString() })
			.where(eq(messages.id, id))
			.returning();
		return rows[0] ?? null;
	}

	/** Edit content — sets editedAt timestamp */
	async updateContent(id: string, content: string): Promise<Message | null> {
		const now = new Date().toISOString();
		const rows = await this.db
			.update(messages)
			.set({ content, editedAt: now, updatedAt: now })
			.where(eq(messages.id, id))
			.returning();
		return rows[0] ?? null;
	}
}
